import { createContext, useContext } from "react";

export const LanguageContext = createContext({ lang: "English", setLang: () => {} });
export const useLanguage = () => useContext(LanguageContext);

export const UI_TEXT = {
  English: {
    appName: "Care Pulse",
    warningsTitle: "Health Warnings",
    warnings: "Warnings",
    loading: "Loading your recovery data...",
    patientNotFound: "Patient profile not found.",
    backToLogin: "Back to Login",
    recoveryInfo: "Recovery Info",
    recoveryInformation: "Recovery Information",
    tabs: { checkin: "Check-in", ai: "AI Chat", voice: "Voice AI", concern: "Alert Doctor" },
    aiTitle: "AI Recovery Assistant",
    aiSubtitle: "Ask anything about your recovery",
    language: "Language",
    remindersTitle: "Daily Reminders",
    remindersGranted: "Notifications enabled! You'll be reminded to check-in and take medicines.",
    remindersDenied: "Please allow notifications in your browser settings.",
    remindersSend: "Enable Reminders",
    bookAmbulance: "Book Ambulance",
    ambulanceConfirmTitle: "Request Ambulance?",
    ambulanceConfirmMsg: "This will send an ambulance request to your hospital.",
    ambulanceConfirm: "Confirm",
    ambulanceCancel: "Cancel",
    ambulanceSent: "Ambulance request sent to hospital!",
    ambulanceSending: "Sending...",
    // Recovery Panel
    currentStatus: "Current Status",
    recoveryScore: "Recovery Score",
    aftercareInstructions: "After-care Instructions",
    dosAndDonts: "Dos & Don'ts",
    precautions: "Precautions",
    nextAppointment: "Next Appointment",
    // Medicine Page
    medicinePage: "Medicine Reminders",
    todayMedicines: "Today's Medicines",
    medicationsCount: (n) => `${n} medications prescribed`,
    prescribedMedicines: "Prescribed Medicines",
    noMedicines: "No medicines prescribed yet",
    doctorsInstructions: "Doctor's Instructions",
    daily: "Daily",
    // Sidebar Menu
    surgeryHistory: "Surgery History",
    medicineReminder: "Medicine Reminder",
    foodRecommendations: "Food Recommendations",
    doctorInstructions: "Doctor Instructions",
    healthWarnings: "⚠️ Health Warnings",
    reminders: "🔔 Reminders",
    ambulance: "🚑 Book Ambulance",
    logout: "Logout",
    // Status labels
    stable: "🟢 Stable",
    needsMonitoring: "🟡 Monitoring",
    highRisk: "🔴 High Risk",
  },
  Telugu: {
    appName: "కేర్ పల్స్",
    loading: "మీ రికవరీ డేటా లోడ్ అవుతోంది...",
    patientNotFound: "రోగి ప్రొఫైల్ కనుగొనబడలేదు.",
    backToLogin: "లాగిన్‌కు తిరిగి వెళ్ళండి",
    recoveryInfo: "రికవరీ సమాచారం",
    recoveryInformation: "రికవరీ సమాచారం",
    tabs: { checkin: "చెక్-ఇన్", ai: "AI చాట్", voice: "వాయిస్ AI", concern: "డాక్టర్‌కు హెచ్చరిక" },
    aiTitle: "AI రికవరీ సహాయకుడు",
    aiSubtitle: "మీ రికవరీ గురించి ఏదైనా అడగండి",
    language: "భాష",
    remindersTitle: "రోజువారీ రిమైండర్లు",
    remindersGranted: "నోటిఫికేషన్‌లు ప్రారంభించబడ్డాయి! చెక్-ఇన్ మరియు మందుల గురించి రిమైండ్ చేయబడతారు.",
    remindersDenied: "దయచేసి బ్రౌజర్ సెట్టింగ్‌లలో నోటిఫికేషన్‌లను అనుమతించండి.",
    remindersSend: "రిమైండర్లు ప్రారంభించు",
    bookAmbulance: "యాంబులెన్స్ బుక్ చేయి",
    ambulanceConfirmTitle: "యాంబులెన్స్ కోరాలా?",
    ambulanceConfirmMsg: "ఇది మీ ఆసుపత్రికి యాంబులెన్స్ అభ్యర్థనను పంపుతుంది.",
    ambulanceConfirm: "నిర్ధారించు",
 
